### PR TITLE
Implements custom seed

### PR DESCRIPTION
**Pull request by ThomAce**
Slight optimization done here and there
Implenetation of custom seed number to generate the same image when same prompts provided with the same seed number. Implementation of project details logging

### CODE REVIEW

**Comment by vitoplantamura** [comment]
hi,

thank you for the PR.

I need to review all the changes more carefully, on a bigger screen than my
phone :-)

Meanwhile, I noticed a problem:

(x) Can you remove the two lines 736 and 737, since "model.read_file" is
already called in one of the caller functions?

A couple more things:

(x) Can you remove lines 602 and 603? And also the comment on line 812?

(x) Can you modify the pre-existing "get_current_time" in order to use
"std::chrono::steady_clock" and then use "get_current_time" in your code
instead of calling "steady_clock" directly?

(x) I don't like the whole "writeLog" part: it's redundant and introduces
new points of failures in the code. It is also useless since the user can
use stdout redirection. I also don't want to write anything to disk during
inference. Can you remove it?

Thanks, Vito

**Comment by ThomAce** [comment]
Hi,

Thanks for the feedback. The model read obviously caused by a copy&paste issue when I updated my fork to SDXL feature.

Removed those commented parts.

Modified the steady clock to using the get current time

I don't like the "user can redirect" approach since this kind of things proven how wrong it could be millions of times. This logging saved me some cases already and it is not writing anything to disc during the inference of course. Just at the beginning.  But, this is your child and I don't wanted to poop into it. I'll remove it from this PR of course and keeping the extra features on my fork like capability to show every steps, logging the operation, etc...

Please check the updated code.

**Comment by vitoplantamura** [comment]
thanks for your time!

So, a couple of things:

(x) you forgot to update the "stable_diffusion_xl" function. The PR, as it
is now, does not compile.

(x) could you remove all the tabs and newlines that make reading the
changeset difficult? For example lines 598, 602, 654-656 etc. etc.

To see the "final look" of the changeset, I go here:

https://github.com/vitoplantamura/OnnxStream/pull/40/files

Thanks, Vito

**Comment by ThomAce** [comment]
Hi,

Thanks for the feedback. Actually, I have performed this copy & paste from VS to github and it seems that the original code that I have downloaded is full of spaces in indents instead of tabs. And several line-ends looked incomplete. I don't know why this happened, but I will reformat the file because when I copy & paste it into github, these extra empty lines appears.

**Comment by ThomAce** [comment]
Hi,

Something is not good.
Even if the file is good on my end, when I copy & paste and check differences it says:
image

**Comment by ThomAce** [comment]
Attached it here for further reference because I can not update the one in github properly. I don't know the reason but everytime when I paste it, random indents were added.

[sd.zip](https://github.com/vitoplantamura/OnnxStream/files/13238609/sd.zip)

**Comment by vitoplantamura** [comment]
hi,

since we had already decided to do it this way (#18), I integrated this functionality myself.

Thanks, Vito

**Pull request closed without merging**
