### PR TITLE
SDXL Turbo support 

### PR DESCRIPTION
**Pull request by AeroX2**
Adding SDXL Turbo support!

The turbo mode can be enabled with the `--turbo` flag and all the updated weights can also be found here:
https://huggingface.co/AeroX2/stable-diffusion-xl-turbo-1.0-onnxstream/tree/main
The model can easily do 1 step inference and has some impressive results.

I've done my best to try and match the formatting as much as possible but let me know if you want some stuff changed.

### CODE REVIEW

**Comment by AeroX2** [comment]
Needs some work on adding the tiled decoder, I thought I got it working but it was just silently failing and showing the previous result :/

**Comment by vitoplantamura** [comment]
Perfect! I did some quick tests on my PC: tiled decoding works too!

A detail: on HF, the "sdxl_vae_decoder_32x32_fp16" directory, required by the tiled decoder, is missing.

Tomorrow I'll try it on the RPI Zero 2.

Thanks, Vito

**Comment by vitoplantamura** [comment]
I was cloning the HF models on my RPI Zero, and the SD card exploded :-)

The 2 models sdxl_vae_decoder_fp16 and sdxl_unet_fp16 are in fp32 precision.

Could you convert them with onnx2txt by specifying CONVERT_TO_FP16 = True?

In the end, the size of the weights will be half and the inference should
be faster.

Thanks, Vito

**Comment by AeroX2** [comment]
Sure thing, just added a new commit on huggingface, let me know how it goes.

**Comment by vitoplantamura** [comment]
perfect thanks!

Can I ask you to delete the two fp32 versions? (ie sdxl_vae_decoder_fp32
and sdxl_unet_fp32)

They are not used in any code path and the "git clone" is faster and takes
up much less disk space for end users.

Thanks, Vito

**Pull request merged**
